#!/bin/sh
#
# A hook script to run after supplying a commit message
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# run rush change after supplying commit message to generage a change log

rush change -b origin/main
echo bfldalfdjkl