trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - LICENSE
      - .vscode/*

pr:
  drafts: false
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - LICENSE

resources:
  repositories:
    - repository: build-pipeline-scripts
      type: git
      ref: master
      name: iModelTechnologies/imodeljs-build-pipeline-scripts
    - repository: itwinjs-core
      type: github
      endpoint: iModelJs
      name: iTwin/itwinjs-core
      ref: refs/heads/master

stages:
- stage: Build
  displayName: Build
  jobs:
    - job: Build
      strategy:
        matrix:
          linux:
            imageName: 'ubuntu-latest'
          # mac:
            # imageName: 'macos-latest'
          windows:
            imageName: 'windows-latest'

      pool:
        vmImage: '$(imageName)'

      steps:

      - checkout: self
        persistCredentials: true
        clean: true

      - task: NodeTool@0
        inputs:
          versionSpec: '18.12.0'
        displayName: 'Install Node.js'

      - script: |
          npm install
        displayName: 'install packages'

      # - script: |
      #     npm ci
      #   displayName: 'npm ci'
      - script: |
          npm run lint
        displayName: 'npm run lint'

      - script: |
           npm run build
        displayName: 'npm run build'

      - script: |
          npm run test:standalone
        displayName: 'npm run test:standalone'
        condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

      - script: |
          npm run test:integration
        displayName: 'npm run test:integration'
        env:
          imjs_buddi_resolve_url_using_region: $(env)
          test_project_id: $(test_project_id)
          test_user_name: $(test_user_name)
          test_user_password: $(test_user_password)
          test_client_id: $(test_client_id)
          test_redirect_uri: $(test_redirect_uri)
          test_scopes: $(test_scopes)
        condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

      - script: |
          npm run documentation
        displayName: 'npm install and build documentation'

      - task: CopyFiles@2
        displayName: 'Copy generated docs to: $(Build.StagingDirectory)/docs/'
        inputs:
          SourceFolder: $(Build.SourcesDirectory)/documentation/
          TargetFolder: $(Build.StagingDirectory)/docs/

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Connector-Framework Docs'
        inputs:
          PathtoPublish: '$(Build.StagingDirectory)/docs/'
          ArtifactName: 'Connector-Framework Docs'

      - bash: |
          checkVersion() {
            localVer=$1
            name=$2

            remoteVer=$(npm view $name version)
            if [ -z "$remoteVer" ]; then
              remoteVer=0.0.0
            fi

            olderVer=$(printf '%s\n' "$localVer" "$remoteVer" | sort -V | head -n1)
            if [ "$localVer" != "$remoteVer" ] && [ "$remoteVer" = "$olderVer" ]; then
              echo true
            else
              echo false
            fi
          }

          version=$(node -p "require('./package.json').version")
          name=$(node -p "require('./package.json').name")
          update=$(checkVersion $version $name)

          if [ "$update" = "true" ] ; then
            echo "package publishing conditions are met."
            shouldPublish=true
          else
            echo "package publishing conditions not met."
            shouldPublish=false
          fi

          echo "##vso[task.setvariable variable=shouldPublish;isOutput=true]$shouldPublish"
          echo "##vso[task.setvariable variable=version;isOutput=true]$version"
          echo "##vso[task.setvariable variable=name;isOutput=true]$name"

        displayName: 'Store Build Info'
        name: info
        condition: and(succeeded(), eq(variables.attempt_publish, true), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Agent.OS'], 'Linux'))

      - bash: |
          echo "shouldPublish: $(info.shouldPublish)"
          echo $(System.DefaultWorkingDirectory)
          pwd
          ls
        displayName: 'Show Build Info'
        condition: and(succeeded(), eq(variables['info.shouldPublish'], 'true'))

      - script: |
          npm pack
        displayName: 'npm pack @itwin/connector-framework'
        condition: and(succeeded(), eq(variables['info.shouldPublish'], 'true'))

      - task: CopyFiles@2
        inputs:
          sourceFolder: $(System.DefaultWorkingDirectory)
          contents: '*.tgz'
          targetFolder: $(Build.ArtifactStagingDirectory)/connector-framework
        displayName: 'Copy @itwin/connector-framework'
        condition: and(succeeded(), eq(variables['info.shouldPublish'], 'true'))

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/connector-framework'
          artifactName: connector-framework
        displayName: 'Publish Connector Framework Artifact'
        condition: and(succeeded(), eq(variables['info.shouldPublish'], 'true'))

- stage: Publish
  displayName: Publish
  condition: and(succeeded(), eq(dependencies.Build.outputs['Build.linux.info.shouldPublish'], 'true'))
  dependsOn: Build
  jobs:
    - template: templates/npmjs-publish-deployment.yaml@build-pipeline-scripts
      parameters:
        path: '*.tgz'
        artifactName: connector-framework
        name: ConnectorFramework
        dryrun: false
    - job: ReleaseTag
      displayName: Release Tag
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - checkout: self
        persistCredentials: true
        clean: true
      - pwsh: |
          $versionNum=(Get-Content ./package.json | ConvertFrom-Json).version
          git config user.name 'imodeljs-admin'
          git config user.email '38288322+imodeljs-admin@users.noreply.github.com'
          git tag -a "release/$versionNum" -m "v$versionNum"
          git push origin "release/$versionNum"
        displayName: 'git tag'

- stage: Validate_Docs
  dependsOn: Build
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'PullRequest', 'Manual'))
  jobs:
      - template: common/config/azure-pipelines/jobs/docs-build.yaml@itwinjs-core
        parameters:
          checkout: itwinjs-core
          useCurrentConnectorFrameworkDocsArtifact: true

- stage: Tag_Docs
  dependsOn: Validate_Docs
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'Manual'))
  jobs:
   - job: Tag_Docs
     displayName: Tag Docs
     pool:
       vmImage: 'ubuntu-latest'
     steps:
     - task: tagBuildOrRelease@0
       displayName: Tag Docs
       inputs:
        type: "Build"
        tags: "hasDocs"
        condition: and(contains(variables['Build.SourceVersionMessage'], '[publish docs]'), not(contains(variables['Build.SourceVersionMessage'], '(dev)')))
